In [1]:
# importing modules and packages
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn import preprocessing

In [5]:
# Import the dataset from the csv file.
import pandas as pd
df = pd.read_csv('../data/large_cat_desc.csv', header=None)

In [8]:
df.columns = [*df.columns[:-1], 'ddG (% ee)']
df.head()

0    1    2    3    4    5    6    7    8    9  ...      3965  \
0  1_1_1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ... -0.833714   
1  1_1_2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ... -0.880495   
2  1_1_3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.104378   
3  1_1_4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ... -0.938972   
4  1_1_5  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.112732   

       3966      3967      3968      3969      3970      3971      3972  \
0 -0.605952 -0.471700 -0.768480 -0.178536 -0.298590 -0.238640 -0.277510   
1 -0.602624 -0.471616 -0.798242 -0.277709 -0.280445 -0.279338 -0.246094   
2  1.789966  1.707972 -0.078629 -1.416062 -1.347984 -1.383415  0.492188   
3 -0.643031 -0.505083 -0.825677 -0.297732 -0.236059 -0.267225  0.028798   
4  0.601039  0.691527  1.360684  0.614598  0.524781  0.570340 -1.518452   

       3973  ddG (% ee)  
0 -0.230633   -0.672194  
1 -1.153164   -1.146684  
2  0.691898    0.276786  
3 -0.691898   -0.672194  
4 -0.230633    1.463011  

[5 rows x 3975 columns]

In [11]:
df.shape
# This is a problem as our n << p
# And if p > n, then there is no longer a unique least squares coefficient estimate. 
# Leat squares will not be a 

(1903, 3975)

In [9]:
# We have lot of rows that have Enantiomeric Excess == 0. These ones we will exclude from the dataset.
df_cleaned = df[df['ddG (% ee)'] != 0]
df_cleaned

0    1    2    3    4    5    6    7    8    9  ...      3965  \
0     1_1_1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ... -0.833714   
1     1_1_2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ... -0.880495   
2     1_1_3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.104378   
3     1_1_4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ... -0.938972   
4     1_1_5  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.112732   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...   
1898  9_9_2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ... -0.880495   
1899  9_9_3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.104378   
1900  9_9_4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ... -0.938972   
1901  9_9_5  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  1.112732   
1902  9_9_6  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.436071   

          3966      3967      3968      3969      3970      3971      3972  \
0    -0.605952 -0.471700 -0.768480 -0.178536 -0.298590 -0.238640 -0.277510   
1    -0.602624 -0.471616 -0.798242 -0.277709 -0.280445 -0.279338 -0.246094   
2     1.789966  1.707972 -0.078629 -1.416062 -1.347984 -1.383415  0.492188   
3    -0.643031 -0.505083 -0.825677 -0.297732 -0.236059 -0.267225  0.028798   
4     0.601039  0.691527  1.360684  0.614598  0.524781  0.570340 -1.518452   
...        ...       ...       ...       ...       ...       ...       ...   
1898 -0.602624 -0.471616 -0.798242 -0.277709 -0.280445 -0.279338 -0.246094   
1899  1.789966  1.707972 -0.078629 -1.416062 -1.347984 -1.383415  0.492188   
1900 -0.643031 -0.505083 -0.825677 -0.297732 -0.236059 -0.267225  0.028798   
1901  0.601039  0.691527  1.360684  0.614598  0.524781  0.570340 -1.518452   
1902 -0.539398 -0.951100  1.110344  1.555441  1.638297  1.598277  1.521070   

          3973  ddG (% ee)  
0    -0.230633   -0.672194  
1    -1.153164   -1.146684  
2     0.691898    0.276786  
3    -0.691898   -0.672194  
4    -0.230633    1.463011  
...        ...         ...  
1898 -1.153164   -1.146684  
1899  0.691898    0.276786  
1900 -0.691898   -0.672194  
1901 -0.230633    1.463011  
1902  1.614430    0.751276  

[1903 rows x 3975 columns]

In [4]:
# Lets separate out the x and y 
X = df_cleaned[['x','y','z']]
y = df_cleaned['ddG (% ee)']

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=101)

In [6]:
# with sklearn
# creating a regression model
model = LinearRegression()
  
# fitting the model
model.fit(X_train, y_train)
  
# making predictions
predictions = model.predict(X_test)

# model evaluation
print('mean_squared_error : ', mean_squared_error(y_test, predictions))
print('mean_absolute_error : ', mean_absolute_error(y_test, predictions))

mean_squared_error :  0.10686574075223941
mean_absolute_error :  0.275571383948475


In [7]:
print('Intercept: \n', model.intercept_)
print('Coefficients: \n', model.coef_)

Intercept: 
 0.4323468984662589
Coefficients: 
 [-0.00122995 -0.00340784 -0.00199706]


In [8]:
sample_predict = np.array([-48.68710019,27.57547822,53.74597739])
model.predict(sample_predict.reshape(1, -1))

C:\Users\dalje\PycharmProjects\ee-predict\venv\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([0.29092283])

In [9]:
coef =  [-0.00122995, -0.00340784, -0.00199706]
intercept = 0.4323468984662589
np.dot(sample_predict, coef) + model.intercept_

0.2909228380412312

In [10]:
from sklearn.cross_decomposition import PLSRegression
model = PLSRegression(n_components=2)
# fitting the model
model.fit(X_train, y_train)
  
# making predictions
predictions = model.predict(X_test)

# model evaluation
print('mean_squared_error : ', mean_squared_error(y_test, predictions))
print('mean_absolute_error : ', mean_absolute_error(y_test, predictions))

mean_squared_error :  0.1063480698362802
mean_absolute_error :  0.27497913508936606


In [11]:
from joblib import dump, load
dump(model, 'pls.joblib') 
clf2 = load('pls.joblib') 
clf2.predict(X[0:1])

array([[0.55539496]])