In [2]:
# importing modules and packages
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn import preprocessing

In [3]:
# Import the dataset from the csv file.
import pandas as pd
df = pd.read_csv('../data/large_cat_desc.csv', header=None)

In [4]:
df.columns = [*df.columns[:-1], 'ddG (% ee)']
#df.head()

In [5]:
df.shape
# This is a problem as our n << p
# And if p > n, then there is no longer a unique least squares coefficient estimate. 
# Leat squares will not be a 

(1903, 3975)

In [6]:
# We have lot of rows that have Enantiomeric Excess == 0. These ones we will exclude from the dataset.
df_cleaned = df[df['ddG (% ee)'] != 0]
df_cleaned.shape

(1903, 3975)

In [4]:
# Lets separate out the x and y 
X = df_cleaned[['x','y','z']]
y = df_cleaned['ddG (% ee)']

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=101)

In [6]:
# with sklearn
# creating a regression model
model = LinearRegression()
  
# fitting the model
model.fit(X_train, y_train)
  
# making predictions
predictions = model.predict(X_test)

# model evaluation
print('mean_squared_error : ', mean_squared_error(y_test, predictions))
print('mean_absolute_error : ', mean_absolute_error(y_test, predictions))

mean_squared_error :  0.10686574075223941
mean_absolute_error :  0.275571383948475


In [7]:
print('Intercept: \n', model.intercept_)
print('Coefficients: \n', model.coef_)

Intercept: 
 0.4323468984662589
Coefficients: 
 [-0.00122995 -0.00340784 -0.00199706]


In [8]:
sample_predict = np.array([-48.68710019,27.57547822,53.74597739])
model.predict(sample_predict.reshape(1, -1))

C:\Users\dalje\PycharmProjects\ee-predict\venv\lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([0.29092283])

In [9]:
coef =  [-0.00122995, -0.00340784, -0.00199706]
intercept = 0.4323468984662589
np.dot(sample_predict, coef) + model.intercept_

0.2909228380412312

In [10]:
from sklearn.cross_decomposition import PLSRegression
model = PLSRegression(n_components=2)
# fitting the model
model.fit(X_train, y_train)
  
# making predictions
predictions = model.predict(X_test)

# model evaluation
print('mean_squared_error : ', mean_squared_error(y_test, predictions))
print('mean_absolute_error : ', mean_absolute_error(y_test, predictions))

mean_squared_error :  0.1063480698362802
mean_absolute_error :  0.27497913508936606


In [11]:
from joblib import dump, load
dump(model, 'pls.joblib') 
clf2 = load('pls.joblib') 
clf2.predict(X[0:1])

array([[0.55539496]])